# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  WORK_DIR_GITHUB: /home/runner/work/cheby_checker
  REB_DIR: ${{ env.WORK_DIR_GITHUB }}/rebound
  REBX_DIR: ${{ env.WORK_DIR_GITHUB }}/reboundx
  JPL_PLANET_EPHEM: ${{ env.REBX_DIR }}/examples/ephem_forces/linux_p1550p2650.440
  JPL_SB_EPHEM: ${{ env.REBX_DIR }}/examples/ephem_forces/sb441-n16.bsp

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        cd ..
        # Install rebound
        export LD_LIBRARY_PATH=${{ env.REB_DIR }}/src:${{ env.REBX_DIR }}/src
        git clone https://github.com/Smithsonian/rebound.git
        make -C $REB_DIR
        # Install reboundx
        git clone -b mpc_dev https://github.com/Smithsonian/reboundx.git
        make -C $REBX_DIR/examples/ephem_forces/
        ls
        tree
        cd cheby_checker
        cp cheby_container/sb441-n16.bsp $REBX_DIR/examples/ephem_forces
    #- name: Lint with flake8
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        export LD_LIBRARY_PATH=$REB_DIR/src:$REBX_DIR/src
        # Set up the server for sockets tests
        python tests/sockets_server_starter_DO_NOT_DELETE.py & 
        pytest
